let extensionWindows=new Map();
import {user} from './live-session.js';
import {bountyConnection as config} from './nova-bounty-config.js';
import {generateWeek,shift,serverFormat,serverInput,serverInstant} from './bounty-schedule.js?v=reset-fix-20260928';
const root=document.querySelector('[data-section="bounties"]'),review=root.querySelector('.r4-layout'),notice=document.getElementById('status');
const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
async function call(body){if(!user)throw Error('Sign in first.');const r=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:config.anonKey,'X-Portal-Token':await user.getIdToken()},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to save. Reload and try again.');return d;}
let saved=[],loaded=false;
const now=new Date(),iso=now.toISOString().slice(0,10),monday=shift(iso,-((now.getUTCDay()+6)%7));
root.querySelector('h1').textContent='Bounties';root.querySelector('.page-heading p').textContent='Set the collection tasks, review submitted evidence, and track decisions.';
const tabs=node('div');tabs.className='admin-workflow-tabs';tabs.setAttribute('role','group');tabs.setAttribute('aria-label','Bounty workspace');const manage=node('section'),history=node('section');manage.className=history.className='hub-card bounty-management';
const panels=[manage,review,history];['Manage Bounties','Review Submissions','Review History'].forEach((name,i)=>{const b=node('button',name);b.type='button';b.onclick=()=>{panels.forEach((p,j)=>p.hidden=i!==j);[...tabs.children].forEach((x,j)=>x.setAttribute('aria-pressed',String(i===j)));notice.hidden=i!==1;document.getElementById('refresh').hidden=i!==1;if(i===0)load();if(i===2)loadHistory();};tabs.append(b);});root.querySelector('.page-heading').after(tabs);root.append(manage,history);
const toolbar=node('div');toolbar.className='bounty-manager-toolbar';const weekLabel=node('label','Week beginning '),week=node('input');week.type='date';week.value=monday;weekLabel.append(week);const search=node('input');search.type='search';search.placeholder='Search bounties';search.setAttribute('aria-label','Search bounties');const add=node('button','+ Add bounty');add.type='button';add.className='primary';const reload=node('button','Refresh');reload.type='button';toolbar.append(weekLabel,search,reload,add);manage.append(toolbar);const message=node('p');message.setAttribute('role','status');manage.append(message);const list=node('div');list.className='table-scroll';manage.append(list);
function rows(){const d=new Date(week.value+'T12:00Z');if(!Number.isFinite(d.getTime()))return [];const mon=shift(week.value,-((d.getUTCDay()+6)%7));const defaults=generateWeek(mon).filter(r=>/^(VSD|VSW|DNW)/.test(r.id));const map=new Map(defaults.map(r=>[r.id,{reference:r.id,title:r.title,body:r.details,startsAt:r.start,endsAt:r.end,points:r.points,status:'published',date:r.id.slice(-8).replace(/(\d{4})(\d{2})(\d{2})/,'$1-$2-$3'),scheduled:true}]));for(const r of saved){const ref=r.payload.reference;if(ref.slice(-8)>=mon.replaceAll('-','')&&ref.slice(-8)<=shift(mon,6).replaceAll('-',''))map.set(ref,{...r,reference:ref,date:r.payload.gameDate,points:r.payload.points});}return [...map.values()].map(r=>{const w=extensionWindows.get(r.reference);return {...r,startsAt:w?.startsAt||r.startsAt,effectiveEndsAt:w?.endsAt||r.endsAt,effectivePoints:w?.points??r.points,boosted:!!w?.boosted,extended:!!w?.extended&&!w?.closed};}).filter(r=>(r.title+' '+r.reference).toLowerCase().includes(search.value.toLowerCase()));}
const fmt=s=>s?'Server time · '+serverFormat(s)+' / Your time · '+new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}):'Not scheduled';
function paint(){list.replaceChildren();const table=node('table');table.className='hub-table';const head=node('tr');['Bounty','Availability','Upload window · server time','Reward',''].forEach(t=>head.append(node('th',t)));table.append(head);for(const r of rows()){const tr=node('tr'),name=node('td');name.append(node('strong',r.title),node('small',r.scheduled?'Recurring schedule':r.status==='draft'?'Saved draft':'Saved settings'));if(r.extended)name.append(node('small','Extended for submissions'));tr.append(name,node('td',r.status!=='published'?r.status:Date.now()<Date.parse(r.startsAt)?'Upcoming':Date.now()>=Date.parse(r.effectiveEndsAt)?'Closed':'Open'),node('td',fmt(r.startsAt)+' → '+fmt(r.effectiveEndsAt)),node('td',r.effectivePoints+' points'+(r.boosted?' · +5 bonus':'')));const cell=node('td'),edit=node('button','Edit');edit.type='button';edit.onclick=()=>editor(r);cell.append(edit);tr.append(cell);table.append(tr);}list.append(table);if(!rows().length)list.append(node('p','No bounties match this view.'));}
async function load(){message.textContent='Loading bounty settings…';try{const content=await call({action:'hub-content-list'});extensionWindows=new Map((content.find(x=>x.kind==='bounty_windows')?.payload||[]).map(w=>[w.reference,w]));saved=content.filter(x=>x.kind==='bounty_content'&&x.payload?.reference);loaded=true;paint();message.textContent='Daily VS, weekly VS and weekly donations. Server midnight is 7 p.m. Pacific. Your local time is shown alongside it.';}catch(e){message.textContent=e.message;}}
week.onchange=paint;search.oninput=paint;reload.onclick=load;add.onclick=()=>editor();
function editor(item){if(!loaded)return;const dialog=node('dialog');dialog.className='admin-edit-dialog bounty-editor';dialog.setAttribute('aria-label',item?'Edit bounty':'Add bounty');const bar=node('div');bar.className='admin-dialog-bar';bar.append(node('strong',item?'Edit bounty':'Add bounty'));const close=node('button','×');close.type='button';close.className='admin-close';close.setAttribute('aria-label','Close bounty editor');close.onclick=()=>dialog.close();bar.append(close);dialog.append(bar);const form=node('form');form.className='hub-card hub-form-grid';const fields={};function field(label,name,type,value){const wrap=node('label',label),input=node(type==='textarea'?'textarea':type==='select'?'select':'input');if(type!=='textarea'&&type!=='select')input.type=type;input.name=name;input.required=true;if(type==='textarea'){input.rows=4;wrap.className='wide';}if(value!==undefined)input.value=value;wrap.append(input);form.append(wrap);fields[name]=input;return input;}
const kind=field('Score collection','kind','select');[['VSD','Daily VS'],['VSW','Weekly VS'],['DNW','Weekly donations']].forEach(([v,t])=>{const o=node('option',t);o.value=v;kind.append(o);});kind.value=item?.reference.slice(0,3)||'VSD';
field('Game date / weekly Monday','date','date',item?.date||week.value);field('Bounty title','title','text',item?.title||'');field('Reward points','points','number',item?.points??10).min=0;fields.points.max=10000;fields.points.step=1;
field('Opens · server time','startsAt','datetime-local',serverInput(item?.startsAt));field('Closes · server time','endsAt','datetime-local',serverInput(item?.endsAt));const state=field('Status','status','select');[['draft','Draft · hidden from members'],['published','Published'],['archived','Archived · uploads closed']].forEach(([v,t])=>{const o=node('option',t);o.value=v;state.append(o);});state.value=item?.status||'draft';field('Screenshot requirements','body','textarea',item?.body||'');
if(item){kind.disabled=true;fields.date.disabled=true;}
function defaults(){if(item)return;const date=fields.date.value;if(!date)return;const mon=shift(date,-((new Date(date+'T12:00Z').getUTCDay()+6)%7));const sample=generateWeek(mon).find(r=>r.id.startsWith(kind.value)&&(kind.value!=='VSD'||r.id.endsWith(date.replaceAll('-',''))));if(sample){fields.title.value=sample.title;fields.body.value=sample.details;fields.startsAt.value=serverInput(sample.start);fields.endsAt.value=serverInput(sample.end);}}
kind.onchange=defaults;fields.date.onchange=defaults;defaults();const help=node('p','Saving updates the member bounty board and upload window. Previous submissions and awarded points stay unchanged.');help.className='wide';form.append(help);const result=node('p');result.className='wide';result.setAttribute('role','status');form.append(result);const save=node('button','Save bounty');save.type='submit';save.className='primary';form.append(save);
form.onsubmit=async e=>{e.preventDefault();const date=fields.date.value,day=new Date(date+'T12:00Z').getUTCDay();if((kind.value==='VSD'&&(day===0))||(kind.value!=='VSD'&&day!==1)){result.textContent=kind.value==='VSD'?'Daily VS runs Monday–Saturday.':'Choose the Monday of the week.';return;}const ref=kind.value+(kind.value==='VSD'?['SUN','MON','TUE','WED','THU','FRI','SAT'][day]:'')+'-'+date.replaceAll('-','');if(!item&&rows().some(r=>r.reference===ref)){result.textContent='That bounty already exists. Close this form and choose Edit.';return;}if(fields.endsAt.value<=fields.startsAt.value){result.textContent='Closing time must be after opening time.';return;}if(!confirm('Save this bounty and its member-site availability?'))return;save.disabled=true;try{await call({action:'hub-content-save',id:item?.id||'',revision:item?.revision||0,kind:'bounty_content',alliance:'NvSP',title:fields.title.value,body:fields.body.value,status:state.value,startsAt:serverInstant(fields.startsAt.value),endsAt:serverInstant(fields.endsAt.value),payload:{reference:ref,gameDate:date,points:Number(fields.points.value)}});dialog.close();week.value=shift(date,-((new Date(date+'T12:00Z').getUTCDay()+6)%7));await load();message.textContent='Bounty saved. Member settings and upload rules updated.';}catch(e){result.textContent=e.message;}finally{save.disabled=false;}};dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
async function loadHistory(){history.replaceChildren(node('h2','Review history'),node('p','The most recent 200 completed decisions.'));try{const data=await call({action:'review-list',scope:'history'});if(!data.length){history.append(node('p','No completed reviews yet.'));return;}for(const r of data){const details=node('details'),summary=node('summary',r.gameDate+' · '+r.bounty+' · '+r.state);details.append(summary,node('p',(r.points??0)+' reward points · '+r.fileCount+' screenshots'),node('p',r.reviewNote||'No review note recorded.'));const page=node('select');page.setAttribute('aria-label','Screenshot page');for(let n=1;n<=r.fileCount;n++){const option=node('option','Screenshot '+n);option.value=n;page.append(option);}const evidence=node('button','View screenshot');evidence.type='button';evidence.onclick=async()=>{try{const d=await call({action:'evidence',batchId:r.id,sequence:Number(page.value)});const a=node('a','Open screenshot');a.href=d.url;a.target='_blank';a.rel='noopener';details.querySelector('a')?.remove();details.append(a);}catch(e){details.append(node('p',e.message));}};if(r.fileCount)details.append(page,evidence);history.append(details);}}catch(e){history.append(node('p',e.message));}}
tabs.children[0].click();
