import {user} from './live-session.js';
import {firebaseConfig} from './firebase-config.js';
import {bountyConnection} from './nova-bounty-config.js';
const endpoint=bountyConnection.endpoint.replace('/nova-bounty','/nova-drive-connect');
const $=id=>document.getElementById(id),status=s=>$('status').textContent=s;
async function call(body){if(!user)throw Error('Sign in to the Portal in this tab, then return here.');const r=await fetch(endpoint,{method:'POST',headers:{apikey:bountyConnection.anonKey,'X-Portal-Token':await user.getIdToken(),'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to connect.');return data;}
async function refresh(){try{const r=await call({action:'status'});$('connect').disabled=false;$('pick').disabled=!r.connected;status(r.rootId?'Private bounty folder connected. Automatic uploads are awaiting integration.':r.connected?'Google connected. Choose the Nova Bounty Evidence folder next.':'Ready to connect your Google account.');}catch(e){status(e.message);}}
$('connect').onclick=async()=>{try{$('connect').disabled=true;const {url}=await call({action:'start'});location.assign(url);}catch(e){status(e.message);$('connect').disabled=false;}};
$('pick').onclick=async()=>{try{if(!window.gapi)throw Error('Google folder picker is still loading. Try again.');$('pick').disabled=true;await new Promise((resolve,reject)=>gapi.load('picker',{callback:resolve,onerror:()=>reject(Error('Unable to load Google folder picker.'))}));const {accessToken}=await call({action:'picker'});const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);new google.picker.PickerBuilder().addView(view).setOAuthToken(accessToken).setDeveloperKey(firebaseConfig.apiKey).setAppId('998333309773').setOrigin(location.origin).setCallback(async data=>{if(data.action===google.picker.Action.PICKED){try{await call({action:'select-folder',folderId:data.docs[0].id});await refresh();}catch(e){status(e.message);}}$('pick').disabled=false;}).build().setVisible(true);}catch(e){status(e.message);$('pick').disabled=false;}};
if(new URLSearchParams(location.search).get('connection')==='failed')status('Google connection was not completed. Try connecting again.');else refresh();
