const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const day=86400000,iso=d=>d.toISOString().slice(0,10),monday=value=>{const d=new Date(value+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return iso(d);};
const fmt=n=>Number(n).toLocaleString();
export function reportSeries(activity,type,weeks=8,today=iso(new Date()),dates=null){
 if(dates){const first=monday(dates.start),last=monday(dates.end);weeks=Math.round((new Date(last+'T00:00:00Z')-new Date(first+'T00:00:00Z'))/(7*day))+1;today=dates.end;}
 const end=monday(today),start=new Date(end+'T00:00:00Z');start.setUTCDate(start.getUTCDate()-(weeks-1)*7);const records=new Map();
 for(const r of activity||[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||r.score==null||!Number.isFinite(Number(r.score)))continue;const key=[r.metric,r.period,r.date].join(':');if(!records.has(key))records.set(key,Number(r.score));}
 const points=[];
 for(let w=0;w<weeks;w++){const d=new Date(start.getTime()+w*7*day),date=iso(d);if(type==='daily_vs'){for(let i=0;i<6;i++){const date=iso(new Date(d.getTime()+i*day));if(date>today||(dates&&date<dates.start))continue;const score=records.get('vs:day:'+date);points.push({date,score:score??null,target:7200000,complete:score!=null,label:date});}}else if(type==='donations'){const score=records.get('donations:week:'+date);points.push({date,score:score??null,target:35000,complete:score!=null,label:'Week of '+date});}else{let total=0,count=0;for(let i=0;i<6;i++){const dateOfDay=iso(new Date(d.getTime()+i*day));if(dates&&(dateOfDay<dates.start||dateOfDay>dates.end))continue;const score=records.get('vs:day:'+dateOfDay);if(score!=null){total+=score;count++;}}const boundaryPartial=!!dates&&(date<dates.start||iso(new Date(d.getTime()+5*day))>dates.end);const weekly=boundaryPartial?undefined:records.get('vs:week:'+date);points.push({date,score:weekly??(count?total:null),target:43200000,complete:weekly!=null||count===6,label:'Week of '+date,days:weekly!=null?6:count,boundaryPartial});}}
 return points;
}
export function renderReports(root,full){
 root.replaceChildren(el('h2','Participation reports'));root.classList.add('participation-reports');const controls=el('div'),type=el('select'),range=el('select');controls.className='report-controls';type.setAttribute('aria-label','Report type');range.setAttribute('aria-label','Report range');for(const [v,l] of [['donations','Weekly donations'],['daily_vs','Daily Alliance Duel / VS'],['weekly_vs','Weekly Alliance Duel / VS']]){const o=el('option',l);o.value=v;type.append(o);}for(const n of [8,4,12]){const o=el('option','Last '+n+' weeks');o.value=n;range.append(o);}controls.append(type,range);root.append(controls);const custom=el('option','Custom dates');custom.value='custom';range.append(custom);
 const start=el('input'),end=el('input');start.type=end.type='date';start.setAttribute('aria-label','Start date');end.setAttribute('aria-label','End date');end.value=iso(new Date());const initial=new Date(monday(end.value)+'T00:00:00Z');initial.setUTCDate(initial.getUTCDate()-49);start.value=iso(initial);
 const dateControls=el('div');dateControls.className='report-date-controls';dateControls.hidden=true;for(const [label,input] of [['Start date',start],['End date',end]]){const wrap=el('label',label);wrap.append(input);dateControls.append(wrap);}const apply=el('button','Apply report');apply.type='button';dateControls.append(apply);const validation=el('p');validation.setAttribute('role','status');controls.after(dateControls,validation);const content=el('div');root.append(content);
 const draw=()=>{validation.textContent='';if(range.value==='custom'&&(!start.value||!end.value||start.value>end.value||new Date(end.value)-new Date(start.value)>366*day)){validation.textContent='Choose a start and end date in order, up to one year apart.';return;}content.replaceChildren();const points=reportSeries(full.activity,type.value,range.value==='custom'?8:Number(range.value),iso(new Date()),range.value==='custom'?{start:start.value,end:end.value}:null),recorded=points.filter(p=>p.score!=null),complete=recorded.filter(p=>p.complete);const summary=el('p');summary.textContent=`${recorded.length} of ${points.length} periods recorded · Total recorded: ${fmt(recorded.reduce((sum,p)=>sum+p.score,0))} · Highest: ${recorded.length?fmt(Math.max(...recorded.map(p=>p.score))):'Not recorded'}`;content.append(summary,el('p','Missing records are gaps, not zero. Weekly VS totals with fewer than six recorded days are partial. Custom VS dates include only selected days; weekly donations use the week containing each selected date. Targets are participation minimums, not spending limits.'));
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('player-report-chart');svg.style.setProperty('width','100%','important');svg.style.setProperty('height','280px','important');svg.style.display='block';svg.setAttribute('viewBox','0 0 760 260');svg.setAttribute('role','img');svg.setAttribute('aria-label',type.selectedOptions[0].textContent+' participation chart; exact values are listed below.');const max=Math.max(points[0]?.target||1,...recorded.map(p=>p.score))*1.12,width=680,base=205,scale=165/max,step=width/points.length;
 const line=document.createElementNS(ns,'line');line.setAttribute('x1','60');line.setAttribute('x2','740');line.setAttribute('y1',base-(points[0]?.target||0)*scale);line.setAttribute('y2',base-(points[0]?.target||0)*scale);line.setAttribute('stroke','currentColor');line.setAttribute('stroke-dasharray','5 5');svg.append(line);const target=document.createElementNS(ns,'text');target.setAttribute('x','60');target.setAttribute('y','22');target.textContent='Target: '+fmt(points[0]?.target||0);svg.append(target);
 points.forEach((p,i)=>{const x=60+i*step;if(p.score!=null){const bar=document.createElementNS(ns,'rect');bar.setAttribute('x',x+2);bar.setAttribute('y',base-p.score*scale);bar.setAttribute('width',Math.max(2,step-4));bar.setAttribute('height',Math.max(2,p.score*scale));bar.setAttribute('fill',!p.complete?'#b99552':'#429e88');const title=document.createElementNS(ns,'title');title.textContent=p.label+': '+fmt(p.score)+(p.complete?'':' (partial)');bar.append(title);svg.append(bar);}else{const text=document.createElementNS(ns,'text');text.setAttribute('x',x+step/2);text.setAttribute('y',base);text.setAttribute('text-anchor','middle');text.textContent='·';svg.append(text);}if(type.value!=='daily_vs'||points.length<=14||i%6===0){const label=document.createElementNS(ns,'text');label.setAttribute('x',x+2);label.setAttribute('y','232');label.textContent=p.date.slice(5);svg.append(label);}});svg.append(line);content.append(svg);
 const detail=el('details');detail.open=false;detail.append(el('summary','Full details'));const table=el('table'),head=el('tr');for(const v of ['Period','Points','Target','Status'])head.append(el('th',v));table.append(head);for(const p of points){const row=el('tr');for(const v of [p.label,p.score==null?'Not recorded':fmt(p.score),fmt(p.target),p.score==null?'Not recorded':!p.complete?`Partial · ${p.days}/6 days`:p.score>=p.target?'Meets target':'Below target'])row.append(el('td',v));table.append(row);}detail.append(table);content.append(detail);};type.onchange=draw;range.onchange=()=>{dateControls.hidden=range.value!=='custom';if(range.value!=='custom')draw();};apply.onclick=draw;draw();
}
