const number=n=>Number(n).toLocaleString();
export const reportLabels={daily_vs:'Daily Alliance Duel / VS',weekly_vs:'Weekly Alliance Duel / VS',donations:'Weekly donations'};
export function reportCanvas(spec,sections=spec.sections){
 const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=250+sections.length*620;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#132f40';
 const text=(s,x,y,size=24)=>{c.font=`${size}px system-ui, sans-serif`;c.fillText(s,x,y,1460);};
 text(spec.name,70,80,44);text(`Alliance: ${spec.alliance}  ·  Server: ${spec.server}  ·  Rank: ${spec.rank}`,70,125);text(`Participation report  |  ${spec.start} — ${spec.end}`,70,166);text(`Generated ${spec.generated} · Actual recorded scores · Missing records are not zero`,70,204,20);
 sections.forEach((section,index)=>{const top=250+index*620,points=section.points,recorded=points.filter(p=>p.score!=null),target=points[0]?.target||0,max=Math.max(target,1,...recorded.map(p=>p.score))*1.12; c.fillStyle='#132f40';text(reportLabels[section.type],70,top+35,32);text(`${recorded.length}/${points.length} periods recorded · Total ${number(recorded.reduce((a,p)=>a+p.score,0))} · Highest ${recorded.length?number(Math.max(...recorded.map(p=>p.score))):'Not recorded'}`,70,top+78,22);
 const left=160,right=1520,base=top+420,height=280,step=(right-left)/Math.max(points.length,1);c.strokeStyle='#d6dfe3';c.lineWidth=1;for(let tick=0;tick<=4;tick++){const value=max*tick/4,y=base-height*tick/4;c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.stroke();c.fillStyle='#425b69';text(value>=1000000?(value/1000000).toFixed(1)+'M':number(Math.round(value)),70,y+6,18);}
 points.forEach((p,i)=>{const x=left+i*step;if(p.score!=null){c.fillStyle=p.complete?'#368978':'#bc8c34';const h=p.score/max*height;c.fillRect(x+1,base-Math.max(2,h),Math.max(1,step-3),Math.max(2,h));if(points.length<=10){c.fillStyle='#132f40';text(number(p.score),x+2,base-h-12,18);}}else{c.fillStyle='#82929a';text('·',x+step/2,base-5,20);}if(i%Math.max(1,Math.ceil(points.length/12))===0||i===points.length-1){c.fillStyle='#425b69';text(p.date.slice(5),x,base+35,18);}});
 c.strokeStyle='#344a58';c.lineWidth=2;c.setLineDash([9,7]);c.beginPath();c.moveTo(left,base-target/max*height);c.lineTo(right,base-target/max*height);c.stroke();c.setLineDash([]);c.fillStyle='#425b69';text(`Dashed line: minimum ${number(target)} · Teal: recorded · Gold: partial week`,70,top+508,21);text(section.type==='donations'?'Weekly donations use the weeks containing the selected dates.':'VS includes selected game dates. Weekly totals with fewer than six days are partial.',70,top+545,21);
 });return canvas;
}
export function pdfFromCanvases(canvases){
 const encoder=new TextEncoder(),chunks=[],offsets=[0];let length=0;const append=data=>{const bytes=typeof data==='string'?encoder.encode(data):data;chunks.push(bytes);length+=bytes.length;};const obj=(id,body)=>{offsets[id]=length;append(`${id} 0 obj\n`);append(body);append('\nendobj\n');};append('%PDF-1.4\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Count ${canvases.length} /Kids [${canvases.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);
 canvases.forEach((canvas,i)=>{const page=3+i*3,img=page+1,content=page+2;obj(page,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /XObject << /Im0 ${img} 0 R >> >> /Contents ${content} 0 R >>`);const bytes=Uint8Array.from(atob(canvas.toDataURL('image/jpeg',0.94).split(',')[1]),x=>x.charCodeAt(0));offsets[img]=length;append(`${img} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`);append(bytes);append('\nendstream\nendobj\n');const scale=Math.min(802/canvas.width,555/canvas.height),w=canvas.width*scale,h=canvas.height*scale,stream=`q ${w} 0 0 ${h} 20 ${595-20-h} cm /Im0 Do Q`;obj(content,`<< /Length ${encoder.encode(stream).length} >>\nstream\n${stream}\nendstream`);});const xref=length;append(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);for(const offset of offsets.slice(1))append(`${String(offset).padStart(10,'0')} 00000 n \n`);append(`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(chunks,{type:'application/pdf'});
}
export async function downloadReport(spec,format){let blob;if(format==='pdf')blob=pdfFromCanvases(spec.sections.map(section=>reportCanvas(spec,[section])));else blob=await new Promise(resolve=>reportCanvas(spec).toBlob(resolve,format==='jpg'?'image/jpeg':'image/png',0.95));if(!blob)throw Error('Unable to create export.');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${spec.name.replace(/[^\p{L}\p{N}_-]+/gu,'-')}-participation-${spec.start}-${spec.end}.${format}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
