export const buildings=[['hospital-1','Hospital I',27,70],['hospital-2','Hospital II',78,40],['hospital-3','Hospital III',34,88],['hospital-4','Hospital IV',66,27],['refinery-1','Refinery I',26,41],['refinery-2','Refinery II',73,70],['science','Science Hub',66,89],['info','Info Center',36,27],['silo','Nuclear Silo',51,55],['arsenal','Arsenal',51,30],['factory','Mercenary Factory',50,87]];
export const availableBuildings=phase=>buildings;
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function issues(plan,publish=false){const errors=[],members=plan.members||[],keys=members.map(m=>m.key),active=members.filter(m=>m.role==='participant');if(!plan.title?.trim())errors.push('Enter a battle name.');if(!plan.start||!Number.isFinite(+new Date(plan.start)))errors.push('Choose the battle date and time.');if(new Set(keys).size!==keys.length)errors.push('A player appears more than once.');if(active.length>20)errors.push('Choose no more than 20 participants.');if(members.length-active.length>10)errors.push('Choose no more than 10 reserves.');for(const phase of ['opening','later']){const used=[];for(const [building,assigned] of Object.entries(plan.assignments?.[phase]||{})){if(!availableBuildings(phase).some(b=>b[0]===building))errors.push('Unknown building assignment.');if(assigned.length>4)errors.push('A building has more than four players.');for(const key of assigned){if(!active.some(m=>m.key===key))errors.push('Only participants can receive building assignments.');if(used.includes(key))errors.push('A player has conflicting assignments within a phase.');used.push(key);}}}if(publish&&!active.length)errors.push('Add at least one participant before publishing.');return [...new Set(errors)];}
export function assignmentText(plan,key,phase){return Object.entries(plan.assignments?.[phase]||{}).filter(([,ids])=>ids.includes(key)).map(([id])=>buildings.find(b=>b[0]===id)?.[1]||id).join(', ')||'Awaiting assignment';}
export function battleMail(plan,time){return `${plan.title} · Team ${plan.team}\nServer time: ${time}\n${plan.notes||''}\n\n`+availableBuildings('opening').map(([id,name])=>{const names=(plan.assignments?.opening?.[id]||[]).map(k=>{const m=plan.members.find(m=>m.key===k);return m?m.name+' ('+(m.duty==='anchor'?'Anchor':'Support')+')':''}).filter(Boolean);return names.length?`${name}: ${names.join(', ')}`:''}).filter(Boolean).join('\n')+`\n\nSubstitutes: ${plan.members.filter(m=>m.role==='reserve').map(m=>m.name).join(', ')||'None listed'}\n\nAnchor: stays to secure the assigned building.\nSupport: may move once the building is secure.`;}
export const mapRails=[['info','refinery-1','hospital-1','hospital-3','factory','silo'],['hospital-4','hospital-2','refinery-2','science','arsenal']];
export function mapHtml(plan,phase){return `<div class="ds-callout-map"><svg class="ds-connectors" aria-hidden="true"></svg><img class="ds-battlefield" src="./desert-storm-map-readable.png" alt="Desert Storm battlefield with assignments beside the map">${mapRails.map((rail,side)=>`<div class="ds-map-rail ds-map-rail-${side}">${rail.map(id=>{const b=buildings.find(b=>b[0]===id),ids=plan.assignments?.[phase]?.[id]||[];return `<button type="button" data-ds-building="${id}" data-ds-drop="${id}" aria-label="${esc(b[1])}: ${ids.length} assigned. Edit assignments"><strong>${esc(b[1])}</strong>${ids.length?ids.map(k=>`<small>${plan.members.find(m=>m.key===k)?.duty==='anchor'?'A':'S'} · ${esc(plan.members.find(m=>m.key===k)?.name||'Player')}</small>`).join(''):'<small>+ Drop player</small>'}</button>`}).join('')}</div>`).join('')}</div>`;}
export function connectMap(root){const map=root.querySelector('.ds-callout-map');if(!map)return;const img=map.querySelector('img'),svg=map.querySelector('svg');const update=()=>{if(!map.isConnected)return;const area=map.getBoundingClientRect(),image=img.getBoundingClientRect();if(!area.width||!image.height)return;svg.setAttribute('viewBox',`0 0 ${area.width} ${area.height}`);for(const [id,label,x,y] of buildings){let hit=map.querySelector('[data-map-hit="'+id+'"]');if(!hit){hit=document.createElement('button');hit.className='ds-map-hit';hit.dataset.mapHit=id;hit.dataset.dsDrop=id;hit.dataset.dsBuilding=id;hit.setAttribute('aria-label','Drop onto '+label);map.append(hit);}hit.style.left=(image.left-area.left+image.width*x/100)+'px';hit.style.top=(image.top-area.top+image.height*y/100)+'px';}svg.innerHTML=buildings.map(([id,,x,y])=>{const box=map.querySelector(`[data-ds-building="${id}"]`).getBoundingClientRect(),left=mapRails[0].includes(id),ax=(left?box.right:box.left)-area.left,ay=box.top+box.height/2-area.top,bx=image.left-area.left+image.width*x/100,by=image.top-area.top+image.height*y/100;return `<path d="M${ax},${ay} L${bx},${by}"/><circle cx="${bx}" cy="${by}" r="3"/>`}).join('');};img.addEventListener('load',update,{once:true});requestAnimationFrame(update);}
