import {esc,issues} from './storm-core.js?v=playbook-20260928';
import {mountDrag} from './storm-drag.js?v=playbook-20260928';
import {coreProblems} from './storm-core-roster.js?v=20260928';
import {monday,participation} from './storm-participation.js?v=20260928';
import {serverValue,serverToUtc} from './shop-calendar-core.js';
import {moveTeamMember,screenshotRows} from './storm-teams-core.js?v=teams-20260928';
export function openTeamBoard({plan,record,items,players,core,penalties,call,author,hasUnsaved,onSaved,onHistory}){
 const dialog=document.createElement('dialog');dialog.className='ds ds-team-board';let boards={},records={},changed=new Set(),selected=null,query='',poolPage=0,message='',busy=false,ocr=[],ocrPage=0,ocrTarget='A:participant',ocrSource=[],ocrMode=false,worker=null,rolePages={};
 const current=plan.team,other=current==='A'?'B':'A',date=plan.start?serverValue(plan.start).slice(0,10):'';
 const candidates=date?items.filter(x=>x.payload?.stormPlan?.team===other&&!x.payload.stormPlan.deletedAt&&x.status!=='archived'&&x.startsAt&&monday(serverValue(x.startsAt))===monday(date)):[];
 if(hasUnsaved)changed.add(current);boards[current]=structuredClone(plan);records[current]=record;
 const fresh=()=>({version:1,assignmentMode:'anchor-support',title:'Desert Storm · Group '+other,team:other,start:plan.start||'',notes:'',members:core.seed(other).filter(m=>!penalties.active(m.key,date||undefined)),assignments:{opening:{},later:{}}});
 const setOther=x=>{records[other]=x||null;boards[other]=x?structuredClone(x.payload.stormPlan):fresh();};setOther(candidates.length===1?candidates[0]:null);
 const poolSize=Math.max(8,Math.min(20,Math.floor((window.innerHeight-470)/40)));
 const recentNote=key=>{const day=boards[current].start?serverValue(boards[current].start).slice(0,10):serverValue(new Date().toISOString()).slice(0,10);const history=items.filter(x=>x.startsAt&&x.payload?.stormPlan&&!x.payload.stormPlan.deletedAt).map(x=>({date:serverValue(x.startsAt).slice(0,10),team:x.payload.stormPlan.team,members:x.payload.stormPlan.members,status:x.status,publishedAt:x.publishedAt}));const info=participation(key,day,history,penalties.entries);return info.bench?'<small class="ds-pool-note bench">Penalty bench</small>':info.recent==='missed'?'<small class="ds-pool-note due">'+(info.older==='missed'?'Missed 2 recorded weeks':'Missed last recorded week')+'</small>':info.recent==='unknown'?'<small class="ds-pool-note">History incomplete</small>':'';};
 const status=text=>{message=text;const node=dialog.querySelector('[data-team-status]');if(node)node.textContent=text;};
 const locate=key=>['A','B'].find(t=>boards[t].members.some(m=>m.key===key));
 function move(key,target){if(busy)return;const [team,role]=target.split(':'),p=players.find(p=>p.key===key)||Object.values(boards).flatMap(p=>p.members).find(p=>p.key===key),before=locate(key);const error=moveTeamMember(boards,p,team,role,{core:core.members,benched:(k,t)=>penalties.active(k,boards[t].start?serverValue(boards[t].start).slice(0,10):date||undefined)});if(error){status(error);return;}if(before)changed.add(before);if(team)changed.add(team);selected=null;message=p.name+(team?' → DS '+team+' · '+(role==='participant'?'Registered':'Substitute'):' returned to available players')+'. Draft changes only.';draw();}
 mountDrag(dialog,{move,announce:status});
 const playerCard=m=>`<div class="ds-team-person"><button data-ds-drag="${esc(m.key)}" class="ds-drag-chip">⠿ ${esc(m.name)}</button>${core.members.some(c=>c.key===m.key)?'<small>🔒 Core</small>':''}<button data-team-history="${esc(m.key)}" aria-label="History for ${esc(m.name)}">History</button><button data-team-remove="${esc(m.key)}" aria-label="Remove ${esc(m.name)}">×</button></div>`;
 function bucket(t,role){const list=boards[t].members.filter(m=>m.role===role),key=t+role,size=role==='participant'?5:3,pages=Math.max(1,Math.ceil(list.length/size));rolePages[key]=Math.min(rolePages[key]||0,pages-1);return `<section class="ds-team-bucket" data-ds-drop="${t}:${role}"><button class="ds-team-zone" data-ds-drop="${t}:${role}">${role==='participant'?'Registered':'Substitutes'} · ${list.length}/${role==='participant'?20:10}</button>${list.slice(rolePages[key]*size,(rolePages[key]+1)*size).map(playerCard).join('')||'<p>Drop members here</p>'}${pages>1?`<div class="ds-team-pager"><button data-role-page="${key}" data-step="-1" ${rolePages[key]===0?'disabled':''}>←</button><small>${rolePages[key]+1}/${pages}</small><button data-role-page="${key}" data-step="1" ${rolePages[key]===pages-1?'disabled':''}>→</button></div>`:''}</section>`;}
 function draw(){const scrollTop=dialog.querySelector('.ds-pool-scroll')?.scrollTop||0;const assigned=new Set(Object.values(boards).flatMap(p=>p.members.map(m=>m.key))),available=players.filter(p=>!assigned.has(p.key)&&p.name.toLowerCase().includes(query.toLowerCase())),pages=Math.max(1,Math.ceil(available.length/poolSize));poolPage=Math.min(poolPage,pages-1);
 dialog.innerHTML=`<header class="ds-head"><div><span class="ds-eyebrow">STEP 2 · REGISTERED & SUBSTITUTES</span><h2>Build both teams.</h2><p>Drag players into DS A or DS B. Or select a name, then a destination.</p></div><button data-team-close>Close</button></header><div class="ds-team-tools"><button data-team-ocr>${ocrMode?'Back to team board':'Upload assignment screenshots'}</button><button data-team-core>Manage Core</button>${candidates.length>1?`<label>Group ${other} plan<select data-partner><option value="">New draft</option>${candidates.map(x=>`<option value="${esc(x.id)}" ${records[other]?.id===x.id?'selected':''}>${esc(x.title)} · ${esc(serverValue(x.startsAt))}</option>`).join('')}</select></label>`:''}<span role="status" data-team-status>${esc(message)}</span></div>${ocrMode?ocrView():`<div class="ds-team-columns"><aside class="ds-team-pool"><h3>Available · ${available.length}</h3><label>Find a player<input type="search" data-team-search value="${esc(query)}" placeholder="Search NvSP"></label><div class="ds-pool-scroll">${available.map(p=>`<div class="ds-team-person"><button class="ds-drag-chip" data-ds-drag="${esc(p.key)}"><span>⠿ ${esc(p.name)}</span>${recentNote(p.key)}</button><button data-team-history="${esc(p.key)}">History</button></div>`).join('')}</div><button data-ds-drop="">Return to available</button></aside>${['A','B'].map(t=>`<section class="ds-team-column"><h2>DS ${t}</h2><label>Plan name<input data-board-field="title" data-team="${t}" value="${esc(boards[t].title)}" maxlength="120"></label><label>Battle starts · Server time<input type="datetime-local" data-board-field="start" data-team="${t}" value="${boards[t].start?esc(serverValue(boards[t].start).slice(0,16)):''}"></label>${bucket(t,'participant')}${bucket(t,'reserve')}</section>`).join('')}</div>`}<footer class="ds-team-footer"><small>Core seats stay locked. Penalty benches are checked for each battle date. Saving creates drafts; use Finalize to publish.</small><button class="ds-primary" data-team-save>Save team drafts</button></footer>`;
 const poolScroll=dialog.querySelector('.ds-pool-scroll');if(poolScroll)poolScroll.scrollTop=scrollTop;
 if(busy)dialog.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);
 }
 function ocrView(){return `<section class="ds-team-ocr"><div class="ds-team-tools"><label>Add these names to<select data-ocr-target>${['A','B'].flatMap(t=>['participant','reserve'].map(r=>`<option value="${t}:${r}" ${ocrTarget===t+':'+r?'selected':''}>DS ${t} · ${r==='participant'?'Registered':'Substitutes'}</option>`)).join('')}</select></label><label>Screenshot language<select data-ocr-language><option value="eng+vie">English / Vietnamese</option><option value="eng+kor">English / Korean</option><option value="eng">English</option></select></label><label>Screenshots<input data-ocr-files type="file" accept="image/png,image/jpeg,image/webp" multiple></label><button data-read-screenshots>Read screenshots</button></div><p>Images are read in your browser. Match names to existing players, check the rows you want, then apply. Nothing saves until you save the drafts.</p><table><thead><tr><th>Use</th><th>Screenshot text</th><th>Existing player</th></tr></thead><tbody>${ocr.slice(ocrPage*6,ocrPage*6+6).map((r,i)=>`<tr><td><input type="checkbox" aria-label="Include row ${ocrPage*6+i+1}" data-ocr-include="${ocrPage*6+i}" ${r.include?'checked':''}></td><td>${esc(r.text)}</td><td><select aria-label="Match row ${ocrPage*6+i+1}" data-ocr-match="${ocrPage*6+i}"><option value="">Skip / no match</option>${players.map(p=>`<option value="${esc(p.key)}" ${p.key===r.key?'selected':''}>${esc(p.name)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>${ocr.length?`<div class="ds-team-pager"><button data-ocr-page="-1" ${!ocrPage?'disabled':''}>←</button><span>${ocrPage+1}/${Math.ceil(ocr.length/6)} · ${ocr.length} lines</span><button data-ocr-page="1" ${(ocrPage+1)*6>=ocr.length?'disabled':''}>→</button><button data-apply-ocr>Apply checked matches to draft</button></div>`:''}</section>`;}
 async function readScreenshots(){const files=[...dialog.querySelector('[data-ocr-files]').files],language=dialog.querySelector('[data-ocr-language]').value;if(!files.length)return status('Choose assignment screenshots first.');if(files.length>6||files.some(f=>f.size>10*1024*1024))return status('Choose up to 6 images, each no larger than 10 MB.');busy=true;draw();try{const mod=await import('https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.esm.min.js');worker=await (mod.default??mod).createWorker(language.split('+'),1,{logger:e=>status('Reading screenshots: '+e.status+' '+Math.round((e.progress||0)*100)+'%')});ocr=[];ocrSource=[];for(const f of files){const result=await worker.recognize(f);ocr.push(...screenshotRows(result.data.text,players));ocrSource.push({filename:f.name,readAt:new Date().toISOString()});}ocrPage=0;message=ocr.length+' lines read. Review matches and check only the players to add.';}catch(e){message='Could not read screenshots. You can assign manually. '+e.message;}finally{await worker?.terminate();worker=null;busy=false;draw();}}
 function applyOcr(){const rows=ocr.filter(r=>r.include),[team,role]=ocrTarget.split(':');if(!rows.length)return status('Check at least one reviewed match.');if(rows.some(r=>!r.key))return status('Choose a player for every checked row.');if(new Set(rows.map(r=>r.key)).size!==rows.length)return status('The same player is checked twice. Uncheck the duplicate.');const draft=structuredClone(boards),touched=new Set();for(const r of rows){const p=players.find(p=>p.key===r.key);const old=['A','B'].find(t=>draft[t].members.some(m=>m.key===r.key));const error=moveTeamMember(draft,p,team,role,{core:core.members,benched:(k,t)=>penalties.active(k,draft[t].start?serverValue(draft[t].start).slice(0,10):date||undefined)});if(error)return status(error);if(old)touched.add(old);touched.add(team);}boards=draft;for(const t of touched)changed.add(t);boards[team].assignmentImports=[...(boards[team].assignmentImports||[]),{sources:ocrSource,reviewedBy:author(),reviewedAt:new Date().toISOString(),count:rows.length}];ocrMode=false;message=rows.length+' reviewed players added to DS '+team+'. Save team drafts to keep them.';draw();}
 async function save(){if(busy)return;const targets=[...changed];if(!targets.length)return status('No team changes to save.');const allKeys=Object.values(boards).flatMap(p=>p.members.map(m=>m.key));if(new Set(allKeys).size!==allKeys.length)return status('A player is in both groups. Move them to one group before saving.');for(const t of targets){const p=boards[t],d=p.start?serverValue(p.start).slice(0,10):'';const errors=[...issues(p),...coreProblems(p,core.members.filter(m=>!penalties.active(m.key,d))),...p.members.filter(m=>penalties.active(m.key,d)).map(m=>m.name+' has an active penalty bench.')];if(errors.length)return status('DS '+t+': '+errors.join(' '));if(items.some(x=>x.id!==records[t]?.id&&x.status!=='archived'&&x.payload.stormPlan.team===t&&x.startsAt===p.start))return status('DS '+t+' already has a plan at this time. Open that plan instead.');}if(targets.some(t=>records[t]?.status==='published')&&!confirm('Saving these changes will return the affected finalized plans to Draft and hide them from members until finalized again. Continue?'))return;busy=true;draw();const completed=[];try{for(const t of targets){const p=boards[t],r=records[t],now=new Date().toISOString();p.assignmentMode='anchor-support';p.createdByName=p.createdByName||author();p.createdAt=p.createdAt||now;p.updatedByName=author();p.updatedAt=now;const result=await call({action:'hub-content-save',id:r?.id||'',revision:r?.revision||0,kind:'event',status:'draft',alliance:'NvSP',title:p.title.trim(),body:p.notes||'',startsAt:p.start,endsAt:new Date(+new Date(p.start)+1800000).toISOString(),payload:{...(r?.payload||{}),category:'Desert Storm',stormPlan:structuredClone(p),timeBasis:'server-pacific-plus-five'}});records[t]={...r,...result,status:'draft',title:p.title,startsAt:p.start,endsAt:new Date(+new Date(p.start)+1800000).toISOString(),payload:{...(r?.payload||{}),stormPlan:structuredClone(p)}};changed.delete(t);completed.push(t);onSaved(t,records[t]);}message='Saved DS '+completed.join(' and DS ')+' drafts. Close to continue to the map.';}catch(e){message=(completed.length?'Saved DS '+completed.join(', ')+'. ':'')+'Remaining drafts were NOT saved: '+e.message+' Your changes are still here.';}finally{busy=false;draw();}}
 dialog.addEventListener('input',e=>{const t=e.target;if(t.hasAttribute('data-team-search')){query=t.value;poolPage=0;const list=dialog.querySelector('.ds-pool-scroll');if(list)list.scrollTop=0;draw();const input=dialog.querySelector('[data-team-search]');input.focus();}if(t.dataset.boardField){try{boards[t.dataset.team][t.dataset.boardField]=t.dataset.boardField==='start'?(t.value?serverToUtc(t.value):''):t.value;changed.add(t.dataset.team);}catch(e){status(e.message);}}});
 dialog.addEventListener('change',e=>{const t=e.target;if(t.hasAttribute('data-partner')){if(changed.has(other)&&!confirm('Discard unsaved changes to DS '+other+'?')){draw();return;}setOther(candidates.find(x=>x.id===t.value));changed.delete(other);draw();}if(t.hasAttribute('data-ocr-target'))ocrTarget=t.value;if(t.dataset.ocrInclude!==undefined)ocr[+t.dataset.ocrInclude].include=t.checked;if(t.dataset.ocrMatch!==undefined)ocr[+t.dataset.ocrMatch].key=t.value;});
 dialog.addEventListener('click',e=>{const t=e.target.closest('button');if(!t||busy)return;if(t.hasAttribute('data-team-close')){if(changed.size&&!confirm('Close without saving these team changes?'))return;dialog.close();}else if(t.hasAttribute('data-team-core'))core.open();else if(t.dataset.teamHistory)onHistory(t.dataset.teamHistory);else if(t.dataset.teamRemove)move(t.dataset.teamRemove,'');else if(t.dataset.poolPage){poolPage+=+t.dataset.poolPage;draw();}else if(t.dataset.rolePage){rolePages[t.dataset.rolePage]+=+t.dataset.step;draw();}else if(t.hasAttribute('data-team-ocr')){ocrMode=!ocrMode;draw();}else if(t.hasAttribute('data-read-screenshots'))readScreenshots();else if(t.dataset.ocrPage){ocrPage+=+t.dataset.ocrPage;draw();}else if(t.hasAttribute('data-apply-ocr'))applyOcr();else if(t.hasAttribute('data-team-save'))save();});
 dialog.addEventListener('cancel',e=>{if(busy||changed.size){e.preventDefault();status('Use Close to leave, or save your team drafts first.');}});dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);draw();dialog.showModal();
}
