import {availableBuildings,esc} from './storm-core.js';
export async function exportPlan(plan,time,format='png'){
 const popup=format==='pdf'?window.open('','_blank'):null;
 if(format==='pdf'&&!popup)throw Error('Allow the print window, then try again.');
 try{
 const img=new Image();img.src=new URL('./desert-storm-map-readable.png',import.meta.url).href;await img.decode();
 const canvas=document.createElement('canvas'),c=canvas.getContext('2d');canvas.width=1800;
 const lines=[];const add=(text,size=28,color='#e8f6f9')=>{c.font=`${size>=34?'bold ':''}${size}px sans-serif`;let line='';for(const word of String(text).split(/\s+/)){if(c.measureText(line+' '+word).width>1630&&line){lines.push({text:line,size,color});line=word;}else line+=(line?' ':'')+word;}lines.push({text:line,size,color});};
 for(const phase of ['opening','later']){add(phase==='opening'?'OPENING PHASE':'AFTER 10 MINUTES',38,'#78e2d6');for(const [id,label] of availableBuildings(phase)){const names=(plan.assignments?.[phase]?.[id]||[]).map(k=>plan.members.find(m=>m.key===k)?.name||'Unknown player');add(label+': '+(names.join(' · ')||'Unassigned'));}add('');}
 add('RESERVES',34,'#78e2d6');add(plan.members.filter(m=>m.role==='reserve').map(m=>m.name).join(' · ')||'None listed');if(plan.notes){add('INSTRUCTIONS',34,'#78e2d6');for(const line of plan.notes.split('\n'))add(line);}
 const mapH=Math.round(1680*img.height/img.width);canvas.height=240+mapH+lines.reduce((n,l)=>n+l.size+18,0)+90;
 c.fillStyle='#092531';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#78e2d6';c.font='bold 24px sans-serif';c.fillText('NOVA SAPPHIRE · DESERT STORM',60,52);c.fillStyle='white';c.font='bold 42px sans-serif';c.fillText(plan.title+' · Team '+plan.team,60,112,1680);c.font='28px sans-serif';c.fillText('Server time: '+time,60,160);c.drawImage(img,60,200,1680,mapH);let y=250+mapH;for(const l of lines){c.fillStyle=l.color;c.font=`${l.size>=34?'bold ':''}${l.size}px sans-serif`;c.fillText(l.text,70,y);y+=l.size+18;}
 if(format==='pdf'){popup.document.title='Desert Storm battle plan';popup.document.body.innerHTML=`<style>body{font:15px/1.5 system-ui;color:#102f3d;margin:24px}h1,h2{color:#135665}img{width:100%;display:block}.phase{break-before:page}li{margin:12px 0;break-inside:avoid}p{white-space:pre-wrap}@page{size:A4 portrait;margin:15mm}</style><h1>${esc(plan.title)} · Team ${esc(plan.team)}</h1><p>Server time: ${esc(time)}</p><img src="${img.src}" alt="Desert Storm battlefield">${['opening','later'].map(phase=>`<section class="phase"><h2>${phase==='opening'?'Opening phase':'After 10 minutes'}</h2><ul>${availableBuildings(phase).map(([id,label])=>`<li><strong>${esc(label)}</strong><br>${esc((plan.assignments?.[phase]?.[id]||[]).map(k=>plan.members.find(m=>m.key===k)?.name||'Unknown player').join(' · ')||'Unassigned')}</li>`).join('')}</ul></section>`).join('')}<h2>Reserves</h2><p>${esc(plan.members.filter(m=>m.role==='reserve').map(m=>m.name).join(' · ')||'None listed')}</p><h2>Instructions</h2><p>${esc(plan.notes||'—')}</p>`;await popup.document.querySelector('img').decode();popup.print();}
 else{const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nova-desert-storm-team-'+plan.team+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 }catch(e){popup?.close();throw e;}
}
